### ISSUE TITLE
review the rbac role names 

### ISSUE THREAD

**Issue by JacobTanenbaum** [openshift/cluster-network-operator#1911]
The role openshift-ovn-kubernetes-sbdb is defined as 

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-ovn-kubernetes-sbdb
  namespace: openshift-ovn-kubernetes
rules:
- apiGroups: [""]
  resources:
  - endpoints
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
 ```

but pods need to use this serviceaccount to get access to leases without needing access to databases. We should review rbac names to ensure they sync with their function
