### ISSUE TITLE
[hypershift] HostedCluster created with tolerations without key results in invalid YAML

### ISSUE THREAD

**Issue by wouterhummelink** [openshift/cluster-network-operator#2682]
When a toleration without the key field set the templates for various network controlers fails to render correct yaml.

The problem is that in pkg/hypershift/hypershift.go the function tolerationsToStringSliceYaml stips lines that have empty fields. If that line is the first line (`- key: ""`) it strips the dash (-) that ahead of the key line.

Reproducer:
```
apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: test
  namespace: hostedcluster
spec:
  autoscaling: {}
  capabilities: {}
  channel: stable-4
  controllerAvailabilityPolicy: SingleReplica
  dns:
    baseDomain: dev.okd4.example.com
  etcd:
    managed:
      storage:
        persistentVolume:
          size: 8Gi
        type: PersistentVolume
    managementType: Managed
  fips: false
  infrastructureAvailabilityPolicy: SingleReplica
  issuerURL: https://kubernetes.default.svc
  networking:
    clusterNetwork:
    - cidr: 10.132.0.0/14
      hostPrefix: 22
    networkType: OVNKubernetes
    serviceNetwork:
    - cidr: 172.31.0.0/16
  olmCatalogPlacement: management
  platform:
    agent:
      agentNamespace: hostedcluster
    type: Agent
  pullSecret:
    name: test-pull-secret
  release:
    image: registry.ci.openshift.org/origin/release-scos@sha256:d74ade7b8c381ef12bf9a77291f4f864e4c282df35d5299419efbee5cc6ead8b
  secretEncryption:
    aescbc:
      activeKey:
        name: test-etcd-encryption-key
    type: aescbc
  services:
  - service: APIServer
    servicePublishingStrategy:
      loadBalancer:
        hostname: api.test.dev.okd4.example.com
      type: LoadBalancer
  - service: Ignition
    servicePublishingStrategy:
      type: Route
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: OIDC
    servicePublishingStrategy:
      type: Route
  sshKey:
    name: test-ssh-authorized-key
  tolerations:
  - effect: NoSchedule
    operator: Exists
  updateService: https://amd64.origin.releases.ci.openshift.org/graph
```
